context:
  version: "1.5.1"

package:
  name: glint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@glint/core/-/core-${{ version }}.tgz
  sha256: 589c7a05637c3e4e928d375113793115f41cfcf1effdc10c0e6dfdb21fdc2b41

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - glint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: TypeScript powered tooling for Glimmer templates
  homepage: https://github.com/typed-ember/glint
  repository: https://github.com/typed-ember/glint

extra:
  recipe-maintainers:
    - danielnachun
